// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8EmDRtxsCAVDrdCzNVAVQD8ZW_u9DyB8',
    appId: '1:1010579740734:web:0742593360110d3663596f',
    messagingSenderId: '1010579740734',
    projectId: 'tracebee-128c8',
    authDomain: 'tracebee-128c8.firebaseapp.com',
    storageBucket: 'tracebee-128c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPg1IKGt3N_djkUf13g4ee1vCWc-ZUxoU',
    appId: '1:1010579740734:android:dc26fc1a142937d563596f',
    messagingSenderId: '1010579740734',
    projectId: 'tracebee-128c8',
    storageBucket: 'tracebee-128c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhNoymYaRHN8iTyYamiS4ztRLfFwd3RWg',
    appId: '1:1010579740734:ios:ba78344c47c8fbeb63596f',
    messagingSenderId: '1010579740734',
    projectId: 'tracebee-128c8',
    storageBucket: 'tracebee-128c8.appspot.com',
    iosClientId: '1010579740734-23d1af4v41bhan329at3k9m66p0g6hrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.traceebeeAdminApp',
  );
}
